require 'hiro/version'
require 'hiro/game/engine'
require 'hiro/game/errors'
require 'hiro/characters/player'
require 'hiro/items/weapon'
require 'hiro/items/sword'
require 'hiro/items/armour'
require 'hiro/items/chest'
